name: recsys_ctr
channels:
  - defaults
dependencies:
  - python=3.6
  - cloudpickle=0.6.1
  - numpy=1.14.3
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - seaborn=0.9
  - click=6.7
  - keras=2.2.0
  - tensorflow-gpu==1.10.0  
  - luigi=2.7.5
  - scipy=1.0.1
  - graphviz
  - pydotplus
  - nltk
  - pip:
    - mlflow
    - keras-metrics
    - diskcache
